version: '3.8'

services:
  flask_app:
    build:
      context: ./flask_app
    ports:
      - "5000:5000"
    networks:
      - testnet

  selenium-hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    networks:
      - testnet

  chrome:
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - testnet

  test-runner:
    build:
      context: ./tests
    depends_on:
      - flask_app
      - chrome
    networks:
      - testnet

networks:
  testnet: